#!/bin/sh

set -e

MOD_NAME=osio

case "${1}" in
remove)
	sed -i "/${MOD_NAME}/d" /etc/initramfs-tools/modules
	if [ -x /usr/sbin/update-initramfs ] && [ -e /etc/initramfs-tools/initramfs.conf ] ; then
		update-initramfs -u
	fi
	;;

purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

*)
	echo "postrm called with unknown argument \`${1}'" >&2
	exit 1
	;;
esac

# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section

exit 0
